/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/admin/login'
    | '/admin/produtos'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/admin/login'
    | '/admin/produtos'
    | '/produto/$slug'
    | '/admin'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/admin/login'
    | '/admin/produtos'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreRoute: typeof SobreRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
  }
}

interface AdminProdutosRouteChildren {
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRoute,
  SobreRoute: SobreRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
